export interface IPhoneCountryInput {
  name: string;
  flag: string;
  code: string;
  dialCode: string;
  mobileNumberLength: number;
}

export const countries: IPhoneCountryInput[] = [
  { name: 'Afghanistan', dialCode: '+93', code: 'AF', mobileNumberLength: 9, flag: '🇦🇫' },
  { name: 'Albania', dialCode: '+355', code: 'AL', mobileNumberLength: 9, flag: '🇦🇱' },
  { name: 'Algeria', dialCode: '+213', code: 'DZ', mobileNumberLength: 9, flag: '🇩🇿' },
  { name: 'Andorra', dialCode: '+376', code: 'AD', mobileNumberLength: 9, flag: '🇦🇩' },
  { name: 'Angola', dialCode: '+244', code: 'AO', mobileNumberLength: 9, flag: '🇦🇴' },
  { name: 'Antigua and Barbuda', dialCode: '+1-268', code: 'AG', mobileNumberLength: 10, flag: '🇦🇬' },
  { name: 'Argentina', dialCode: '+54', code: 'AR', mobileNumberLength: 10, flag: '🇦🇷' },
  { name: 'Armenia', dialCode: '+374', code: 'AM', mobileNumberLength: 8, flag: '🇦🇲' },
  { name: 'Australia', dialCode: '+61', code: 'AU', mobileNumberLength: 9, flag: '🇦🇺' },
  { name: 'Austria', dialCode: '+43', code: 'AT', mobileNumberLength: 13, flag: '🇦🇹' },
  { name: 'Azerbaijan', dialCode: '+994', code: 'AZ', mobileNumberLength: 9, flag: '🇦🇿' },
  { name: 'Bahamas', dialCode: '+1-242', code: 'BS', mobileNumberLength: 10, flag: '🇧🇸' },
  { name: 'Bahrain', dialCode: '+973', code: 'BH', mobileNumberLength: 8, flag: '🇧🇭' },
  { name: 'Bangladesh', dialCode: '+880', code: 'BD', mobileNumberLength: 11, flag: '🇧🇩' },
  { name: 'Barbados', dialCode: '+1-246', code: 'BB', mobileNumberLength: 10, flag: '🇧🇧' },
  { name: 'Belarus', dialCode: '+375', code: 'BY', mobileNumberLength: 9, flag: '🇧🇾' },
  { name: 'Belgium', dialCode: '+32', code: 'BE', mobileNumberLength: 10, flag: '🇧🇪' },
  { name: 'Belize', dialCode: '+501', code: 'BZ', mobileNumberLength: 7, flag: '🇧🇿' },
  { name: 'Benin', dialCode: '+229', code: 'BJ', mobileNumberLength: 8, flag: '🇧🇯' },
  { name: 'Bhutan', dialCode: '+975', code: 'BT', mobileNumberLength: 8, flag: '🇧🇹' },
  { name: 'Bolivia', dialCode: '+591', code: 'BO', mobileNumberLength: 8, flag: '🇧🇴' },
  { name: 'Bosnia and Herzegovina', dialCode: '+387', code: 'BA', mobileNumberLength: 8, flag: '🇧🇦' },
  { name: 'Botswana', dialCode: '+267', code: 'BW', mobileNumberLength: 8, flag: '🇧🇼' },
  { name: 'Brazil', dialCode: '+55', code: 'BR', mobileNumberLength: 11, flag: '🇧🇷' },
  { name: 'Brunei', dialCode: '+673', code: 'BN', mobileNumberLength: 8, flag: '🇧🇳' },
  { name: 'Bulgaria', dialCode: '+359', code: 'BG', mobileNumberLength: 9, flag: '🇧🇬' },
  { name: 'Burkina Faso', dialCode: '+226', code: 'BF', mobileNumberLength: 8, flag: '🇧🇫' },
  { name: 'Burundi', dialCode: '+257', code: 'BI', mobileNumberLength: 8, flag: '🇧🇮' },
  { name: 'Cambodia', dialCode: '+855', code: 'KH', mobileNumberLength: 9, flag: '🇰🇭' },
  { name: 'Cameroon', dialCode: '+237', code: 'CM', mobileNumberLength: 8, flag: '🇨🇲' },
  { name: 'Canada', dialCode: '+1', code: 'CA', mobileNumberLength: 10, flag: '🇨🇦' },
  { name: 'Cape Verde', dialCode: '+238', code: 'CV', mobileNumberLength: 7, flag: '🇨🇻' },
  { name: 'Central African Republic', dialCode: '+236', code: 'CF', mobileNumberLength: 7, flag: '🇨🇫' },
  { name: 'Chad', dialCode: '+235', code: 'TD', mobileNumberLength: 8, flag: '🇹🇩' },
  { name: 'Chile', dialCode: '+56', code: 'CL', mobileNumberLength: 9, flag: '🇨🇱' },
  { name: 'China', dialCode: '+86', code: 'CN', mobileNumberLength: 11, flag: '🇨🇳' },
  { name: 'Colombia', dialCode: '+57', code: 'CO', mobileNumberLength: 10, flag: '🇨🇴' },
  { name: 'Comoros', dialCode: '+269', code: 'KM', mobileNumberLength: 7, flag: '🇰🇲' },
  { name: 'Congo', dialCode: '+242', code: 'CG', mobileNumberLength: 9, flag: '🇨🇬' },
  { name: 'Costa Rica', dialCode: '+506', code: 'CR', mobileNumberLength: 8, flag: '🇨🇷' },
  { name: 'Croatia', dialCode: '+385', code: 'HR', mobileNumberLength: 9, flag: '🇭🇷' },
  { name: 'Cuba', dialCode: '+53', code: 'CU', mobileNumberLength: 8, flag: '🇨🇺' },
  { name: 'Cyprus', dialCode: '+357', code: 'CY', mobileNumberLength: 8, flag: '🇨🇾' },
  { name: 'Czech Republic', dialCode: '+420', code: 'CZ', mobileNumberLength: 9, flag: '🇨🇿' },
  { name: 'Denmark', dialCode: '+45', code: 'DK', mobileNumberLength: 8, flag: '🇩🇰' },
  { name: 'Djibouti', dialCode: '+253', code: 'DJ', mobileNumberLength: 8, flag: '🇩🇯' },
  { name: 'Dominica', dialCode: '+1-767', code: 'DM', mobileNumberLength: 10, flag: '🇩🇲' },
  { name: 'Dominican Republic', dialCode: '+1-809', code: 'DO', mobileNumberLength: 10, flag: '🇩🇴' },
  { name: 'East Timor', dialCode: '+670', code: 'TL', mobileNumberLength: 7, flag: '🇹🇱' },
  { name: 'Ecuador', dialCode: '+593', code: 'EC', mobileNumberLength: 9, flag: '🇪🇨' },
  { name: 'Egypt', dialCode: '+20', code: 'EG', mobileNumberLength: 10, flag: '🇪🇬' },
  { name: 'El Salvador', dialCode: '+503', code: 'SV', mobileNumberLength: 8, flag: '🇸🇻' },
  { name: 'Equatorial Guinea', dialCode: '+240', code: 'GQ', mobileNumberLength: 7, flag: '🇬🇶' },
  { name: 'Eritrea', dialCode: '+291', code: 'ER', mobileNumberLength: 7, flag: '🇪🇷' },
  { name: 'Estonia', dialCode: '+372', code: 'EE', mobileNumberLength: 8, flag: '🇪🇪' },
  { name: 'Eswatini', dialCode: '+268', code: 'SZ', mobileNumberLength: 8, flag: '🇸🇿' },
  { name: 'Ethiopia', dialCode: '+251', code: 'ET', mobileNumberLength: 9, flag: '🇪🇹' },
  { name: 'Fiji', dialCode: '+679', code: 'FJ', mobileNumberLength: 7, flag: '🇫🇯' },
  { name: 'Finland', dialCode: '+358', code: 'FI', mobileNumberLength: 10, flag: '🇫🇮' },
  { name: 'France', dialCode: '+33', code: 'FR', mobileNumberLength: 9, flag: '🇫🇷' },
  { name: 'Gabon', dialCode: '+241', code: 'GA', mobileNumberLength: 7, flag: '🇬🇦' },
  { name: 'Gambia', dialCode: '+220', code: 'GM', mobileNumberLength: 7, flag: '🇬🇲' },
  { name: 'Georgia', dialCode: '+995', code: 'GE', mobileNumberLength: 9, flag: '🇬🇪' },
  { name: 'Germany', dialCode: '+49', code: 'DE', mobileNumberLength: 11, flag: '🇩🇪' },
  { name: 'Ghana', dialCode: '+233', code: 'GH', mobileNumberLength: 9, flag: '🇬🇭' },
  { name: 'Greece', dialCode: '+30', code: 'GR', mobileNumberLength: 10, flag: '🇬🇷' },
  { name: 'Grenada', dialCode: '+1-473', code: 'GD', mobileNumberLength: 10, flag: '🇬🇩' },
  { name: 'Guatemala', dialCode: '+502', code: 'GT', mobileNumberLength: 8, flag: '🇬🇹' },
  { name: 'Guinea', dialCode: '+224', code: 'GN', mobileNumberLength: 8, flag: '🇬🇳' },
  { name: 'Guinea-Bissau', dialCode: '+245', code: 'GW', mobileNumberLength: 8, flag: '🇬🇼' },
  { name: 'Guyana', dialCode: '+592', code: 'GY', mobileNumberLength: 7, flag: '🇬🇾' },
  { name: 'Haiti', dialCode: '+509', code: 'HT', mobileNumberLength: 8, flag: '🇭🇹' },
  { name: 'Honduras', dialCode: '+504', code: 'HN', mobileNumberLength: 8, flag: '🇭🇳' },
  { name: 'Hungary', dialCode: '+36', code: 'HU', mobileNumberLength: 9, flag: '🇭🇺' },
  { name: 'Iceland', dialCode: '+354', code: 'IS', mobileNumberLength: 7, flag: '🇮🇸' },
  { name: 'India', dialCode: '+91', code: 'IN', mobileNumberLength: 10, flag: '🇮🇳' },
  { name: 'Indonesia', dialCode: '+62', code: 'ID', mobileNumberLength: 11, flag: '🇮🇩' },
  { name: 'Iran', dialCode: '+98', code: 'IR', mobileNumberLength: 10, flag: '🇮🇷' },
  { name: 'Iraq', dialCode: '+964', code: 'IQ', mobileNumberLength: 10, flag: '🇮🇶' },
  { name: 'Ireland', dialCode: '+353', code: 'IE', mobileNumberLength: 10, flag: '🇮🇪' },
  { name: 'Israel', dialCode: '+972', code: 'IL', mobileNumberLength: 9, flag: '🇮🇱' },
  { name: 'Italy', dialCode: '+39', code: 'IT', mobileNumberLength: 10, flag: '🇮🇹' },
  { name: 'Jamaica', dialCode: '+1-876', code: 'JM', mobileNumberLength: 10, flag: '🇯🇲' },
  { name: 'Japan', dialCode: '+81', code: 'JP', mobileNumberLength: 11, flag: '🇯🇵' },
  { name: 'Jordan', dialCode: '+962', code: 'JO', mobileNumberLength: 9, flag: '🇯🇴' },
  { name: 'Kazakhstan', dialCode: '+7', code: 'KZ', mobileNumberLength: 10, flag: '🇰🇿' },
  { name: 'Kenya', dialCode: '+254', code: 'KE', mobileNumberLength: 9, flag: '🇰🇪' },
  { name: 'Kiribati', dialCode: '+686', code: 'KI', mobileNumberLength: 5, flag: '🇰🇮' },
  { name: 'Korea', dialCode: '+82', code: 'KR', mobileNumberLength: 10, flag: '🇰🇷' },
  { name: 'Kuwait', dialCode: '+965', code: 'KW', mobileNumberLength: 8, flag: '🇰🇼' },
  { name: 'Kyrgyzstan', dialCode: '+996', code: 'KG', mobileNumberLength: 9, flag: '🇰🇬' },
  { name: 'Laos', dialCode: '+856', code: 'LA', mobileNumberLength: 8, flag: '🇱🇸' },
  { name: 'Latvia', dialCode: '+371', code: 'LV', mobileNumberLength: 8, flag: '🇱🇻' },
  { name: 'Lebanon', dialCode: '+961', code: 'LB', mobileNumberLength: 8, flag: '🇱🇧' },
  { name: 'Lesotho', dialCode: '+266', code: 'LS', mobileNumberLength: 8, flag: '🇱🇸' },
  { name: 'Liberia', dialCode: '+231', code: 'LR', mobileNumberLength: 7, flag: '🇱🇷' },
  { name: 'Libya', dialCode: '+218', code: 'LY', mobileNumberLength: 9, flag: '🇱🇾' },
  { name: 'Liechtenstein', dialCode: '+423', code: 'LI', mobileNumberLength: 8, flag: '🇱🇮' },
  { name: 'Lithuania', dialCode: '+370', code: 'LT', mobileNumberLength: 8, flag: '🇱🇹' },
  { name: 'Luxembourg', dialCode: '+352', code: 'LU', mobileNumberLength: 9, flag: '🇱🇺' },
  { name: 'Madagascar', dialCode: '+261', code: 'MG', mobileNumberLength: 9, flag: '🇲🇬' },
  { name: 'Malawi', dialCode: '+265', code: 'MW', mobileNumberLength: 9, flag: '🇲🇼' },
  { name: 'Malaysia', dialCode: '+60', code: 'MY', mobileNumberLength: 9, flag: '🇲🇾' },
  { name: 'Maldives', dialCode: '+960', code: 'MV', mobileNumberLength: 7, flag: '🇲🇻' },
  { name: 'Mali', dialCode: '+223', code: 'ML', mobileNumberLength: 8, flag: '🇲🇱' },
  { name: 'Malta', dialCode: '+356', code: 'MT', mobileNumberLength: 8, flag: '🇲🇹' },
  { name: 'Marshall Islands', dialCode: '+692', code: 'MH', mobileNumberLength: 7, flag: '🇲🇭' },
  { name: 'Mauritania', dialCode: '+222', code: 'MR', mobileNumberLength: 8, flag: '🇲🇷' },
  { name: 'Mauritius', dialCode: '+230', code: 'MU', mobileNumberLength: 7, flag: '🇲🇺' },
  { name: 'Mexico', dialCode: '+52', code: 'MX', mobileNumberLength: 10, flag: '🇲🇽' },
  { name: 'Micronesia', dialCode: '+691', code: 'FM', mobileNumberLength: 7, flag: '🇫🇲' },
  { name: 'Moldova', dialCode: '+373', code: 'MD', mobileNumberLength: 8, flag: '🇲🇩' },
  { name: 'Monaco', dialCode: '+377', code: 'MC', mobileNumberLength: 9, flag: '🇲🇨' },
  { name: 'Mongolia', dialCode: '+976', code: 'MN', mobileNumberLength: 8, flag: '🇲🇳' },
  { name: 'Montenegro', dialCode: '+382', code: 'ME', mobileNumberLength: 8, flag: '🇲🇪' },
  { name: 'Morocco', dialCode: '+212', code: 'MA', mobileNumberLength: 9, flag: '🇲🇦' },
  { name: 'Mozambique', dialCode: '+258', code: 'MZ', mobileNumberLength: 9, flag: '🇲🇿' },
  { name: 'Myanmar', dialCode: '+95', code: 'MM', mobileNumberLength: 8, flag: '🇲🇲' },
  { name: 'Namibia', dialCode: '+264', code: 'NA', mobileNumberLength: 9, flag: '🇳🇦' },
  { name: 'Nauru', dialCode: '+674', code: 'NR', mobileNumberLength: 7, flag: '🇳🇷' },
  { name: 'Nepal', dialCode: '+977', code: 'NP', mobileNumberLength: 10, flag: '🇳🇵' },
  { name: 'Netherlands', dialCode: '+31', code: 'NL', mobileNumberLength: 10, flag: '🇳🇱' },
  { name: 'New Zealand', dialCode: '+64', code: 'NZ', mobileNumberLength: 9, flag: '🇳🇿' },
  { name: 'Nicaragua', dialCode: '+505', code: 'NI', mobileNumberLength: 8, flag: '🇳🇮' },
  { name: 'Niger', dialCode: '+227', code: 'NE', mobileNumberLength: 8, flag: '🇳🇪' },
  { name: 'Nigeria', dialCode: '+234', code: 'NG', mobileNumberLength: 11, flag: '🇳🇬' },
  { name: 'North Macedonia', dialCode: '+389', code: 'MK', mobileNumberLength: 8, flag: '🇲🇰' },
  { name: 'Norway', dialCode: '+47', code: 'NO', mobileNumberLength: 8, flag: '🇳🇴' },
  { name: 'Oman', dialCode: '+968', code: 'OM', mobileNumberLength: 8, flag: '🇴🇲' },
  { name: 'Pakistan', dialCode: '+92', code: 'PK', mobileNumberLength: 10, flag: '🇵🇰' },
  { name: 'Palau', dialCode: '+680', code: 'PW', mobileNumberLength: 7, flag: '🇵🇼' },
  { name: 'Panama', dialCode: '+507', code: 'PA', mobileNumberLength: 8, flag: '🇵🇦' },
  { name: 'Papua New Guinea', dialCode: '+675', code: 'PG', mobileNumberLength: 8, flag: '🇵🇬' },
  { name: 'Paraguay', dialCode: '+595', code: 'PY', mobileNumberLength: 9, flag: '🇵🇾' },
  { name: 'Peru', dialCode: '+51', code: 'PE', mobileNumberLength: 9, flag: '🇵🇪' },
  { name: 'Philippines', dialCode: '+63', code: 'PH', mobileNumberLength: 10, flag: '🇵🇭' },
  { name: 'Poland', dialCode: '+48', code: 'PL', mobileNumberLength: 9, flag: '🇵🇱' },
  { name: 'Portugal', dialCode: '+351', code: 'PT', mobileNumberLength: 9, flag: '🇵🇹' },
  { name: 'Qatar', dialCode: '+974', code: 'QA', mobileNumberLength: 8, flag: '🇶🇦' },
  { name: 'Romania', dialCode: '+40', code: 'RO', mobileNumberLength: 9, flag: '🇷🇴' },
  { name: 'Russia', dialCode: '+7', code: 'RU', mobileNumberLength: 10, flag: '🇷🇺' },
  { name: 'Rwanda', dialCode: '+250', code: 'RW', mobileNumberLength: 9, flag: '🇷🇼' },
  { name: 'Saint Kitts and Nevis', dialCode: '+1-869', code: 'KN', mobileNumberLength: 10, flag: '🇰🇳' },
  { name: 'Saint Lucia', dialCode: '+1-758', code: 'LC', mobileNumberLength: 10, flag: '🇱🇨' },
  { name: 'Saint Vincent and the Grenadines', dialCode: '+1-784', code: 'VC', mobileNumberLength: 10, flag: '🇻🇨' },
  { name: 'Samoa', dialCode: '+685', code: 'WS', mobileNumberLength: 7, flag: '🇼🇸' },
  { name: 'San Marino', dialCode: '+378', code: 'SM', mobileNumberLength: 9, flag: '🇸🇲' },
  { name: 'Sao Tome and Principe', dialCode: '+239', code: 'ST', mobileNumberLength: 7, flag: '🇸🇹' },
  { name: 'Saudi Arabia', dialCode: '+966', code: 'SA', mobileNumberLength: 9, flag: '🇸🇦' },
  { name: 'Senegal', dialCode: '+221', code: 'SN', mobileNumberLength: 9, flag: '🇸🇳' },
  { name: 'Serbia', dialCode: '+381', code: 'RS', mobileNumberLength: 8, flag: '🇷🇸' },
  { name: 'Seychelles', dialCode: '+248', code: 'SC', mobileNumberLength: 7, flag: '🇸🇨' },
  { name: 'Sierra Leone', dialCode: '+232', code: 'SL', mobileNumberLength: 8, flag: '🇸🇱' },
  { name: 'Singapore', dialCode: '+65', code: 'SG', mobileNumberLength: 8, flag: '🇸🇬' },
  { name: 'Slovakia', dialCode: '+421', code: 'SK', mobileNumberLength: 9, flag: '🇸🇰' },
  { name: 'Slovenia', dialCode: '+386', code: 'SI', mobileNumberLength: 8, flag: '🇸🇮' },
  { name: 'Solomon Islands', dialCode: '+677', code: 'SB', mobileNumberLength: 7, flag: '🇸🇧' },
  { name: 'Somalia', dialCode: '+252', code: 'SO', mobileNumberLength: 8, flag: '🇸🇴' },
  { name: 'South Africa', dialCode: '+27', code: 'ZA', mobileNumberLength: 9, flag: '🇿🇦' },
  { name: 'South Sudan', dialCode: '+211', code: 'SS', mobileNumberLength: 9, flag: '🇸🇸' },
  { name: 'Spain', dialCode: '+34', code: 'ES', mobileNumberLength: 9, flag: '🇪🇸' },
  { name: 'Sri Lanka', dialCode: '+94', code: 'LK', mobileNumberLength: 9, flag: '🇱🇰' },
  { name: 'Sudan', dialCode: '+249', code: 'SD', mobileNumberLength: 9, flag: '🇸🇩' },
  { name: 'Suriname', dialCode: '+597', code: 'SR', mobileNumberLength: 7, flag: '🇸🇷' },
  { name: 'Sweden', dialCode: '+46', code: 'SE', mobileNumberLength: 9, flag: '🇸🇪' },
  { name: 'Switzerland', dialCode: '+41', code: 'CH', mobileNumberLength: 9, flag: '🇨🇭' },
  { name: 'Syria', dialCode: '+963', code: 'SY', mobileNumberLength: 9, flag: '🇸🇾' },
  { name: 'Taiwan', dialCode: '+886', code: 'TW', mobileNumberLength: 9, flag: '🇹🇼' },
  { name: 'Tajikistan', dialCode: '+992', code: 'TJ', mobileNumberLength: 9, flag: '🇹🇯' },
  { name: 'Tanzania', dialCode: '+255', code: 'TZ', mobileNumberLength: 9, flag: '🇹🇿' },
  { name: 'Thailand', dialCode: '+66', code: 'TH', mobileNumberLength: 9, flag: '🇹🇭' },
  { name: 'Togo', dialCode: '+228', code: 'TG', mobileNumberLength: 8, flag: '🇹🇬' },
  { name: 'Tonga', dialCode: '+676', code: 'TO', mobileNumberLength: 7, flag: '🇹🇴' },
  { name: 'Trinidad and Tobago', dialCode: '+1-868', code: 'TT', mobileNumberLength: 10, flag: '🇹🇹' },
  { name: 'Tunisia', dialCode: '+216', code: 'TN', mobileNumberLength: 8, flag: '🇹🇳' },
  { name: 'Turkey', dialCode: '+90', code: 'TR', mobileNumberLength: 10, flag: '🇹🇷' },
  { name: 'Turkmenistan', dialCode: '+993', code: 'TM', mobileNumberLength: 8, flag: '🇹🇲' },
  { name: 'Tuvalu', dialCode: '+688', code: 'TV', mobileNumberLength: 5, flag: '🇹🇻' },
  { name: 'Uganda', dialCode: '+256', code: 'UG', mobileNumberLength: 9, flag: '🇺🇬' },
  { name: 'Ukraine', dialCode: '+380', code: 'UA', mobileNumberLength: 9, flag: '🇺🇦' },
  { name: 'United Arab Emirates', dialCode: '+971', code: 'AE', mobileNumberLength: 9, flag: '🇦🇪' },
  { name: 'United Kingdom', dialCode: '+44', code: 'GB', mobileNumberLength: 10, flag: '🇬🇧' },
  { name: 'United States', dialCode: '+1', code: 'US', mobileNumberLength: 10, flag: '🇺🇸' },
  { name: 'Uruguay', dialCode: '+598', code: 'UY', mobileNumberLength: 8, flag: '🇺🇾' },
  { name: 'Uzbekistan', dialCode: '+998', code: 'UZ', mobileNumberLength: 9, flag: '🇺🇿' },
  { name: 'Vanuatu', dialCode: '+678', code: 'VU', mobileNumberLength: 7, flag: '🇻🇺' },
  { name: 'Vatican City', dialCode: '+379', code: 'VA', mobileNumberLength: 9, flag: '🇻🇦' },
  { name: 'Venezuela', dialCode: '+58', code: 'VE', mobileNumberLength: 10, flag: '🇻🇪' },
  { name: 'Vietnam', dialCode: '+84', code: 'VN', mobileNumberLength: 10, flag: '🇻🇳' },
  { name: 'Yemen', dialCode: '+967', code: 'YE', mobileNumberLength: 9, flag: '🇾🇪' },
  { name: 'Zambia', dialCode: '+260', code: 'ZM', mobileNumberLength: 9, flag: '🇿🇲' },
  { name: 'Zimbabwe', dialCode: '+263', code: 'ZW', mobileNumberLength: 9, flag: '🇿🇼' },
];
